# Generated by Django 2.0.2 on 2020-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, verbose_name='用户名')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
                ('adminname', models.CharField(max_length=25, verbose_name='用户名')),
            ],
        ),
    ]
